# 3: Linear Regression with One Variable

## A. Model Representation 

* This is *supervised learning*
* This is a *regression problem* because we are predicting a number
* EX: Diabetes progression prediction

|BMI|Diabetes Progression|
|-|-|
|32.1|151|
|21.6|75|
|30.6|141|
|22.6|97|

* Notations:
  * $m$ = # of training examples
  * $x$ = input variable(s)/feature(s)
  * $y$ = output variable(s)/target(s)
  * $(x,y)$ = single training example
  * $(x_i, y_i)$ = the i-th training example
    * Ex: $(x_1, y_1) = (32.1, 151)$
  * $\hat y$ = the predicted output
* Goal: develop a training set, use the training set on a learning algorithm to generate some sort of model/predictor, then use that model on a developed test set
  
> **The Linear Regression Model (Univariate Linear Regression):**
> 
> $$ f(x)_{w,x} = wx + b $$
> 
> Where $w$ and $x$ are the parameters/coefficients of the model

## B. Squared Error Cost Function

$$ J(w,b) = \frac{1}{2m}\sum_{i=1}^m \left(\hat y^{(i)}-y^{(i)}\right)^2 = \frac{1}{2m}\sum_{i=1}^m \left(f_{w,b}(x^{(i)})-y^{(i)}\right)^2 $$

Where $m$ is the number of training examples.

* The goal is you want to find a linear regression model (a $w$ and $b$) so that $\hat y^{(i)}$ is close to $y^{(i)}$ for all $(x^{(i)}, y^{(i)})$

## C. `numpy` - Python Library Dealing With Arrays

* much faster/more optimized than a normal list in Python
* these arrays are indexed just like normal lists in Python, but they also can be indexed in unique ways (as seen with 2D arrays)

In [1]:
import numpy as np

# create a numpy array (1-D) from a normal python list
np_1d_arr = np.array([1, 2, 3, 4, 5])
print(np_1d_arr)

[1 2 3 4 5]


* You can also create 2-D arrays with numpy (or any dimension of arrays with numpy, but 2D is helpful for manipulating data in data sience/bioinformatics)
* You can index differently with numpy arrays - just do row comma column instead of a set of brackets for the row and column

In [2]:
np_2d_arr = np.array([[1,2,3], [4,5,6]])
print('Third element on second row:', np_2d_arr[1,2])

Third element on second row: 6


* Here are some other useful functions with numpy arrays:

In [3]:
# check dimensions
dim = np_2d_arr.ndim
print('Dimensions of the 2D numpy array:', dim)

# check the shape (number of rows and columns)
arr_shape = np_2d_arr.shape
print('Shape of the 2D numpy array:', arr_shape)
# Shape can also be indexed to get just the rows or just the columns
print('Number of rows in the 2D array:', arr_shape[0])

Dimensions of the 2D numpy array: 2
Shape of the 2D numpy array: (2, 3)
Number of rows in the 2D array: 2


* Array slicing is done as follows:

In [4]:
big_array = np.array([1,2,3,4,5,6,7])
sub_array = big_array[1:5] # index from 1 to 4 (the last index is NOT included)
print(sub_array)

[2 3 4 5]


In [5]:
# slice from a certain index to the end of the array
sub_array = big_array[4:]
print(sub_array)

[5 6 7]


In [6]:
# slice from the beginning to a certain index (but keep in mind that index won't be included)
sub_array = big_array[:4]
print(sub_array)

[1 2 3 4]


In [9]:
# special indexing

big_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(big_array[1, 1:4])
print(big_array[0:2, 2])
print(big_array[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


## D. Plotting with `matplotlib`

* We can make various different plots of our data using the package `matplotlib`
  * There are many plotting libraries, but we will use this one for this class
* 

In [18]:
import matplotlib.pyplot as plt

X_train = [[1, 2, 3, 4, 5, 6], [2, 4, 6, 8, 10, 12]]
plt.scatter(x=X_train[0], y=X_train[1], c='b', marker='x', label='our actual values')
plt.title('Diabetes Progression Prediction (DISCLAIMER: not real values)') # set the title
plt.xlabel('BMI') # set the label for the x-axis
plt.ylabel('Diabetes Progression') # set the label for the y-axis
plt.legend() # use this command to display the legend
plt.show() # show the plot