# 1.1: Intro to MATLAB

If you have never used MATLAB before, then you can use this notebook to learn some basics about MATLAB. 

## Hello World Program

Every time you need to start with writing a Hello World program. We can use the `display()` function to display text to the screen.

In [1]:
display('Hello world')

Hello world



## Vectors and Matrices

MATLAB is built around being able to manipulate vectors and matrices. As such, we should first come up with some mathematical definitions to understand what vectors and matrices are:

A **matrix** is essentially a table of numbers. A matrix $A$ looks something like this:

**CODE FOR MATRIX TO GO HERE**

A **vector** is a 1D matrix (meaning that it has only 1 in a given dimension). Vectors could look something like this:

This os a *row vector*:
$$
v = [a_1, a_2, ... , a_n]
$$

This is a *column vector*:

**CODE FOR VERTICAL VECTOR TO GO HERE LATER**

If we want to create a vector, we can use the following notation to create a vector:

In [4]:
v1 = [1 2 3 4] % this creates a row vector
v2 = [1; 2; 3; 4] % this creates a column vector


v1 =

     1     2     3     4


v2 =

     1
     2
     3
     4




When looking at the code above, it is important to notice the different notation depending on the vector you want to use. **Column vectors and row vectors are thought of differently in the world of linear algebra** so it's important to keep your syntax in mind when defining your vectors.

To create a matrix you can use the following code:

In [3]:
A1 = [2 3 4; 5 6 7]


A1 =

     2     3     4
     5     6     7




This creates a 2 by 3 matrix in memory. 

If you want to store a range of values in a matrix/vector, you can use the `:` operator to step through a range of integer values, as seen in the following code:

In [5]:
v1 = 1:20


v1 =

     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16    17    18    19    20




you can also add another `:` to indicate how much you want to step by, like this:

In [6]:
v2 = -10:0.5:10


v2 =

  Columns 1 through 16

  -10.0000   -9.5000   -9.0000   -8.5000   -8.0000   -7.5000   -7.0000   -6.5000   -6.0000   -5.5000   -5.0000   -4.5000   -4.0000   -3.5000   -3.0000   -2.5000

  Columns 17 through 32

   -2.0000   -1.5000   -1.0000   -0.5000         0    0.5000    1.0000    1.5000    2.0000    2.5000    3.0000    3.5000    4.0000    4.5000    5.0000    5.5000

  Columns 33 through 41

    6.0000    6.5000    7.0000    7.5000    8.0000    8.5000    9.0000    9.5000   10.0000




In the notation above, the syntax is `LOWER_BOUND:STEP:UPPER_BOUND`

You can also use the `linspace()` function to step while having a fixed vector size, as seen in the following code:

In [7]:
v3 = linspace(-10,10,40)


v3 =

  Columns 1 through 16

  -10.0000   -9.4872   -8.9744   -8.4615   -7.9487   -7.4359   -6.9231   -6.4103   -5.8974   -5.3846   -4.8718   -4.3590   -3.8462   -3.3333   -2.8205   -2.3077

  Columns 17 through 32

   -1.7949   -1.2821   -0.7692   -0.2564    0.2564    0.7692    1.2821    1.7949    2.3077    2.8205    3.3333    3.8462    4.3590    4.8718    5.3846    5.8974

  Columns 33 through 40

    6.4103    6.9231    7.4359    7.9487    8.4615    8.9744    9.4872   10.0000




## Filling Matrices and Random Numbers

If you want a vector/matrix filled entirely with a specific value, then you can call a function which is called the number that you want to fill with. For example, if you want to fill a matrix completely of 1s, then you could say:

In [9]:
M1 = ones(2,1) % Create a 2x1 matrix completely filled with 1s
M2 = zeros(3,4) % Create a 3x4 matrix completely filled with 0s


M1 =

     1
     1


M2 =

     0     0     0     0
     0     0     0     0
     0     0     0     0




You can also generate random numbers in MATLAB, which is a common operation in a lot of programming. The `rand` function lets you generate a random number for you:

In [10]:
k1 = rand
k2 = randn


k1 =

    0.8147


k2 =

    1.8339




The `rand` function will give you uniformily distributed real numbers between 0 and 1 (meaning there is an equal probability of getting any real number from 0 to 1). If you want to get random numbers from a larger range, you can use the `randn` function will give you a random number based on the standard Normal distribution. This means that you could get negative numbers as low as say -3 or as large as say 3 but you will most likely get values around 0 since it's from a Normal distribution.



## Concatenating Vectors/Matrices

If you want to combine vectors/matrices then you will need to perform operations to **concatenate** them, which is the CS word for combining them. If you have two vectors `u1` and `u2`, then you can concatenate them in the following way:

In [11]:
v1 = [1 2 3]
v2 = 0:5
v3 = [v1,v2]


v1 =

     1     2     3


v2 =

     0     1     2     3     4     5


v3 =

     1     2     3     0     1     2     3     4     5




Be careful however - YOU CAN'T CONCATENATE TO MATRICES THAT HAVE DIFFERENT DIMENSIONS

## Indexing Into Vectors and Matrices

MATLAB is different than C++ and Java because MATLAB is a **1-based indexing language** which means the first value is referenced at position 1 (this is a big switch for CS students who are used to C++ or Java). The following code shows how to index into a vector:

In [14]:
q1 = 0:0.5:10
q1(1) % get the first element of the vector
q1(2) = 0 % set the second element of the vector to 0
q1(end) % get the last element of the vector
q1(end-1) = 0 % set the second-to-last element of the vector to 0


q1 =

  Columns 1 through 16

         0    0.5000    1.0000    1.5000    2.0000    2.5000    3.0000    3.5000    4.0000    4.5000    5.0000    5.5000    6.0000    6.5000    7.0000    7.5000

  Columns 17 through 21

    8.0000    8.5000    9.0000    9.5000   10.0000


ans =

     0


q1 =

  Columns 1 through 16

         0         0    1.0000    1.5000    2.0000    2.5000    3.0000    3.5000    4.0000    4.5000    5.0000    5.5000    6.0000    6.5000    7.0000    7.5000

  Columns 17 through 21

    8.0000    8.5000    9.0000    9.5000   10.0000


ans =

    10


q1 =

  Columns 1 through 16

         0         0    1.0000    1.5000    2.0000    2.5000    3.0000    3.5000    4.0000    4.5000    5.0000    5.5000    6.0000    6.5000    7.0000    7.5000

  Columns 17 through 21

    8.0000    8.5000    9.0000         0   10.0000




Matrices are a bit more complicated because you have to reference both a row and a column. You always reference the row first and then the column.

In [15]:
B1 = [1:3; 4:6; 7:9]
r = B1(2,2) % Create a variable are and initialize it to the value in row 2 column 2 in B1


B1 =

     1     2     3
     4     5     6
     7     8     9


r =

     5




## The Difference Between Standard Operations and Dot Operations

In MATLAB you get will get different results (and sometimes errors) if you run `.*` or `./` instead of `*` or `/`. `*` is **standard matrix multiplication**. When you perform this operation, the resulting value will be a *matrix* (that is assuming that you can even perform matrix multiplication). `.*` means **elementwise multiplication** which means that you multiply the values at each corresponding element in the matrix/vector. There are a lot of bugs that occur in MATLAB code because of the distinction between these operations, so be careful when writing your MATLAB code!

## Functions

There are built-in functions like `sin` and `cos` but what if you want to over and over compute the function $f(x) = \frac{x \cos(10x)}{x^2}$? We can write our own **function** that will compute these values. 

There are two choices that you can make for user-defined functions:

* *anonymous functions:* the function operation that you are trying to define can be coded in just one line with one output value
* *function file:* need a `.m` file with specific function syntax. 

Here are some examples of functions:

In [ ]:
%%%%% ANONYMOUS FUNCTION
x1 = 0:0.5:10; % Coarse discretization
x2 = 0:0.1:10; % Finer discretization
x3 = 0:0.01:10; % Really fine discretization

f = @(x) x .* cos(10*x) ./ (x .^ 2); % THIS IS THE ANONYMOUS FUNCTION

y1 = f(x1);
y2 = f(x2);
y3 = f(x3);

figure
plot(x1,y1,'-o',x2,y2,'-s',x3,y3,'-*')

In [ ]:
%%%%%%%% FUNCTION FILE SYNTAX
function y = myfunc(x)

    y = x .* cos(10*x) ./ (x.^2);

end

## `for` Loops

In coding, we can use a loop if we want to iteratively do the same action over and over again. Here is an example of how to use a `for` loop in MATLAB:

In [5]:
sum = 0

for j = 1:5

    sum = sum + j ^ 2;

end

disp("The final sum is: ")
disp(sum)


sum =

     0

The final sum is: 
    55




> **EXAMPLE:** Write a `for` loop that accesses each entry of a vector `x = 0:0.5:10` and displays it to the screen. 

In [8]:
x = 0:0.5:10;

for j = 1:numel(x)

    disp(x(j))

end

     0

    0.5000

     1

    1.5000

     2

    2.5000

     3

    3.5000

     4

    4.5000

     5

    5.5000

     6

    6.5000

     7

    7.5000

     8

    8.5000

     9

    9.5000

    10




In [1]:
x = 0:0.5:10;

for n = 1:0.1:5

    y = x.^n;

end


disp(y(10))

   1.8453e+03




## `while` Loops

A `while` loop is used when you do not know the exact number of iterations you want to do but you know the condition for when you want to stop iterating. This means that you iterate while a condition is true.

In [66]:
x = rand;

while x < 0.5
    
    disp(x);
    x = rand;
    
end

disp('DID IT: Finally got the number')
disp(x)

    0.0170

    0.1209

DID IT: Finally got the number
    0.8627




## Conditional Branching

You want the computer to do something when one thing is true and another something if it is false.

> **EXAMPLE:** Write a function that takes a scalar $x$ as input and:
>
> * If $x>0$, return 1 (as output)
> * If $x < 0$, return -1 (as output)
> * If $x=0$, return 0 (as output)

In [75]:
%%file files/checksign.m

function y = checkSign(x)

    if x > 0
        y = 1;
        
    elseif x < 0
        y = -1;
        
    else
        y = 0;
        
    end

end

checkSign(5)

Created file 'C:\Users\bushn\Home\Notes\STEM-Notes\MATH350 Numerical Methods\Chapter 1 - Numerical Algorithms\files\checksign.m'.


In [76]:
checkSign(5)

Undefined function 'checkSign' for input arguments of type 'double'.



> **EXAMPLE:** Write a function that takes a vector $x$ as input and:
> 
> * If $x(n) = 0$, replace it with  1
> * If $x(n) < 0$, replace it with 0
> * If $x(n) > 0$, do nothing

In [77]:
%%file files/replacevalues.m

function x = replaceValues(x)

    for n = 1:numel(x)
    
        if x(n) == 0
            x(n) == 1
            
        elseif x(n) < 0
            x(n) == 0
            
        end
    
    end

end

Created file 'C:\Users\bushn\Home\Notes\STEM-Notes\MATH350 Numerical Methods\Chapter 1 - Numerical Algorithms\files\replacevalues.m'.


In [78]:
x = [1 -3 0 2 -5];
y = replaceValues(x)

Undefined function 'replaceValues' for input arguments of type 'double'.

